### ISSUE TITLE
AttributeError: module 'pairinteraction' has no attribute 'KetAtom'

### ISSUE THREAD

**Issue by dimitsev** [pairinteraction/pairinteraction#317]
In a fresh python venv, I installed pairinteraction (v2.2.2) via `pip install pairinteraction` and then immediately ran `python` and `import pairinteraction as pi` and `pi.KetAtom`. It threw `AttributeError: module 'pairinteraction' has no attribute 'KetAtom'`. Same for other attributes. This happened on both Ubuntu 24.04 LTS (python 3.12.9) and Windows 11 (python 3.9.9).

Edit: Everything works if I use `import pairinteraction.complex as pi` or `import pairinteraction.real as pi`. Please, either change your [quickstart guides](https://www.pairinteraction.org/pairinteraction/master/tutorials/examples_python/quick_start.html) or make `import pairinteraction as pi` work.

**Comment by johannes-moegerle** [comment]
`import pairinteraction as pi` should now work with the new release v2.3.0
also the documentation is now published for different releases
